### ISSUE TITLE
Crash: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mikalai-t** [FairwindsOps/polaris#510]
### Installation Process
Downloaded from `https://github.com/FairwindsOps/polaris/releases/download/3.1.5/polaris_3.1.5_linux_amd64.tar.gz`

### Polaris Version

```
Polaris version:3.1.5
```

### Expected Behavior

Polaris shouldn't crash but return a result of check.

### Actual Behavior

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x13eec52]

goroutine 1 [running]:
github.com/fairwindsops/polaris/pkg/validator.(*PodResult).removeSuccessfulResults(0x0)
	/go/src/github.com/fairwindsops/polaris/pkg/validator/output.go:99 +0x22
github.com/fairwindsops/polaris/pkg/validator.(*Result).removeSuccessfulResults(0xc00032f598)
	/go/src/github.com/fairwindsops/polaris/pkg/validator/output.go:88 +0x41
github.com/fairwindsops/polaris/pkg/validator.(*AuditData).RemoveSuccessfulResults(0xc00032f760)
	/go/src/github.com/fairwindsops/polaris/pkg/validator/output.go:43 +0xcf
github.com/fairwindsops/polaris/pkg/validator.RunAudit(0x0, 0x0, 0xc00044b380, 0x0, 0xc0001f7800, 0x11, 0x13, 0x0, 0xc00031c210, 0x1, ...)
	/go/src/github.com/fairwindsops/polaris/pkg/validator/fullaudit.go:54 +0x3ad
github.com/fairwindsops/polaris/cmd/polaris.runAndReportAudit(0x1bc9580, 0xc000108000, 0x0, 0x0, 0xc00044b380, 0x0, 0xc0001f7800, 0x11, 0x13, 0x0, ...)
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/audit.go:86 +0x1cd
github.com/fairwindsops/polaris/cmd/polaris.glob..func1(0x27a7cc0, 0xc0001af110, 0x1, 0x7)
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/audit.go:64 +0x138
github.com/spf13/cobra.(*Command).execute(0x27a7cc0, 0xc0001af0a0, 0x7, 0x7, 0x27a7cc0, 0xc0001af0a0)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x27a81c0, 0x2739220, 0xc0000a4750, 0xc000553f50)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
github.com/fairwindsops/polaris/cmd/polaris.Execute(0x187bd5b, 0x5)
	/go/src/github.com/fairwindsops/polaris/cmd/polaris/root.go:84 +0x56
main.main()
	/go/src/github.com/fairwindsops/polaris/main.go:27 +0x36
```

### Steps to Reproduce

1. There is a long list of YAMLs including `Kustomize` configs in the `base` dir
2. Run `polaris audit --audit-path ./base --set-exit-code-on-danger --set-exit-code-below-score 80 --only-show-failed-tests true`

### Additional Context

* CircleCI pipeline
* Executor based on Docker image `bash:5`

### References

no

**Comment by rbren** [comment]
Looks like this got fixed. Thanks!
